app_token:
  ''
uid:
   - ''
   - ''
   - ''
   - ''
   - ''

ov2500_requests:
  server_ip: ['', '']

  user:
    ''
  pwd:
    ''

  login_url:
    ''
  notifications_url:
    ''
  getAPList_url:
    ''

  alarm_data:
    type: GetTrapDataRequestObject
    uniqueRequestId: 0
    sessionKey: 0
    name: null
    request: null
    filterBy: ALL
    mapIds: null
    deviceMap: null
    apGroups: null
    severities:
      - critical
      - major
    ack: 'FALSE'
    count: 1000
    timeRange: null
    pageNumber: 0
    pageSize: 1000
    trapNames: [ ]


zabbix_request:
  url:
    ''
  header:
    {"Content-Type": "application/json-rpc"}


  request_json:
    jsonrpc: '2.0'
    method: host.get
    params:
      output:
        - name
        - snmp_error
      filter:
        snmp_available: '2'
    auth: 
    id: 1


olt_info:
  old_ip: ''
  new_ip: ''
  snmp_oid: ''
